### ISSUE TITLE
pip install missing version.py file

### ISSUE THREAD

**Issue by bernease** [popylar/popylar#13]
(py3.5)D-10-18-251-41:~ bernease$ pip install popylar
Collecting popylar
  Downloading popylar-0.1.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/k3/y9t32c8j2ps84nr1kklhn0hr0000gn/T/pip-build-6qn75uz9/popylar/setup.py", line 7, in <module>
        with open(ver_file) as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'popylar/version.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/k3/y9t32c8j2ps84nr1kklhn0hr0000gn/T/pip-build-6qn75uz9/popylar/
You are using pip version 8.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by arokem** [comment]
I believe this was addressed in #14, and in currently released 0.1.7
